name: CI

on: [push]

jobs:
  
  linux-build:
    runs-on: ubuntu-latest
    steps: 
      - name: install sbcl
        run:  apt update && apt install -yy sbcl
      - name: compile binary
        run: sbcl 
          --no-userinit 
          --load main.lisp 
          --eval "(sb-ext:save-lisp-and-die \"a.out\" :toplevel 'main :executable t)"
        
        
