name: CI

on: [push]

jobs:
  
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: install sbcl
        run:  sudo apt-get update && sudo apt-get install -y sbcl
      - name: compile binary
        run: sbcl 
          --no-userinit
          --disable-debugger 
          --load main.lisp 
          --eval "(sb-ext:save-lisp-and-die \"a.out\" :toplevel 'main :executable t)"
      - name: Zip Release
        uses: TheDoctor0/zip-release@v0.2.1
        
        
